name: Continuous Integration and Continous Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Installing Gridsome CLI tool
        run: npm install --global @gridsome/cli

      - name: Installing packages
        run: npm install

      - name: Build Gridsome site
        run: |
          gridsome build
          echo "Gridsome site is successfully build"
        env:
          SAVEDDOTIO_KEY: ${{ secrets.SAVEDDOTIO_KEY }}
          SAVEDDOTIO_DEVKEY: ${{ secrets.SAVEDDOTIO_DEVKEY }}
