name: Continuous Integration and Continous Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Installing Gridsome CLI tool
        run: npm install --global @gridsome/cli

      - name: Installing packages
        run: npm install

      - name: Build Site
        run: |
          gridsome build
          echo "Gridsome site is successfully build"

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
